name: ntlm
description: NTLM authentication for Dart/Flutter
version: 1.0.0
homepage: https://github.com/mrbbot/ntlm
author: MrBBot <me@mrbbot.co.uk>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: any
  utf: any
  pointycastle: ^1.0.0
  fixnum: any

dev_dependencies:
  test: any
